### ISSUE TITLE
listen probably shouldn't pause another listen

### ISSUE THREAD

**Issue by ppannuto** [tock/tockloader#22]
Then you get in a situation where it's a nested set of terminals who resume listening. The bigger problem is once the _second_ listen is active, a _third_ tockloader is then blocked from running as "another tockloader process is active".

Basically, we should special-case the pausing of another tockloader process such that if the new one is a listen, it bails out instead.

**Comment by bradjc** [comment]
If we dive into this, we should probably flesh out the functionality to cover all of the cases like this.
