### ISSUE TITLE
Feature Request: Timestamp option for listen

### ISSUE THREAD

**Issue by ppannuto** [tock/tockloader#27]
Add an option for tockloader to prepend lines with a timestamp during listen, useful for long-running sessions where you want to review what happened

**Comment by ppannuto** [comment]
Also maybe `--count` that puts a message counter in front, for quickly skimming how many successful lines happened between failures

**Comment by bradjc** [comment]
I was going to reply that this would be very hard to do...but miniterm has provisions for it so it was reasonably straightforward.

It's not a perfect implementation (only works if the newline is the last thing received from the serial port), but it can be improved as needed.
