### ISSUE TITLE
Ubuntu subsystem does not autofind "tock" board

### ISSUE THREAD

**Issue by bradjc** [tock/tockloader#49]
imix and hail try to name the FTDI serial port with "tock" in the name, but for some reason that doesn't work with Ubuntu for Windows. I'm not sure if it is supposed to, or if we need to use the serial library in a different way.

**Comment by alevy** [comment]
Fwiw it works for me on nixos, so at least it's not generally a Linux Linux problem

**Comment by bradjc** [comment]
I reproduced this. There isn't a lot of documentation on serial for WSL, and I don't think the FTDI fields are propagated. Users will have to manually figure out which `/dev/ttyS` is correct and specify it.
