### ISSUE TITLE
Uncaught exception on Python 3.8+

### ISSUE THREAD

**Issue by ppannuto** [tock/tockloader#62]
Every tockloader run terminates with an exception:

```
$ tockloader list
[INFO   ] No device name specified. Using default name "tock".
[INFO   ] Using "/dev/cu.usbserial-c098e513000e - Hail IoT Module - TockOS - Hail IoT Module - TockOS".
┌──────────────────────────────────────────────────┐
│ App 0                                            |
└──────────────────────────────────────────────────┘
  Name:                  hail
  Enabled:               True
  Sticky:                False
  Total Size in Flash:   65536 bytes


[INFO   ] Finished in 1.884 seconds
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
```

I think this is related to https://docs.python.org/3/whatsnew/3.8.html#threading, which changes how exceptions in background threads are handled.

This was likely always a "problem"; I'm guessing that we are technically supposed to in some way cleanly shut down the server thread rather than just killing it off. It's not really a problem-problem, since this is an exception that triggers during shutdown, so we don't really care, but cosmetically it's pretty undesirable.

I spent a few minutes poking around, but it's not immediately obvious what the right fix is.

**Comment by bradjc** [comment]
I believe I fixed this by adding a try catch in https://github.com/tock/tockloader/commit/5e9eb121e282ce43b46aa907cee677e20a3eadfa

I will of course see if it still happens in some cases, but hopefully this exception will no longer print.
