### ISSUE TITLE
Rust port branch

### ISSUE THREAD

**Issue by alexandruradovici** [tock/tockloader#98]
One of my students (@george-cosma) has started porting tockloader to Rust, using this branch https://github.com/UPB-CS-OpenSourceUpstream/tockloader/tree/rust-port. 

I was wondering of we can open a `rust-port` branch in this repository to start sending PRs here, so that he can get feedback from the whole Tock team.

**Comment by brghena** [comment]
Per the call today, we created a separate repo in the Tock org here: https://github.com/tock/tockloader-rs
